# Generated by Django 3.1.1 on 2020-10-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
