# Generated by Django 3.1.1 on 2020-10-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_feira'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feira',
        ),
    ]
